export const storeInfoData = {
  id: "store-main",
  businessName: "New Adhikari Traders",
  address: "Kathmandu, Bagmati Province 44600",
  city: "Kathmandu",
  province: "Bagmati Province 44600",
  phone: "985-1145065",
  hours: "7:00 AM – 8:00 PM (Daily)",
  latitude: 27.7172,
  longitude: 85.324,
  socialLinks: {
    facebook: "https://facebook.com",
    whatsapp: "https://wa.me/9779851145065",
    viber: "viber://chat?number=%2B9779851145065",
  },
};

export const heroSlidesData = [
  {
    id: "power-tools",
    categoryTag: "POWER TOOLS & MACHINERY",
    headline: "Professional Heavy-Duty Power Tools & Workshop Equipment",
    subtext:
      "Authorized distributor for Bosch, Makita, and DeWalt in Kathmandu. Factory warranty backed with genuine manufacturer serials.",
    ctaText: "Shop Power Tools",
    ctaAction: "power-tools",
    categoryId: "power-tools",
    bgImage: "/images/hero/hero-power-tools-main.webp",
    mainImage: "/images/hero/hero-power-tools-main.webp",
    detailImage: "/images/hero/hero-power-tools-detail.webp",
    detailBadge: "Heavy-Duty 850W Pro Class",
    sortOrder: 1,
  },
  {
    id: "electrical",
    categoryTag: "COMMERCIAL & RESIDENTIAL ELECTRICAL",
    headline: "Grade-A Copper Cables & Flame-Retardant Switchgear",
    subtext:
      "Supplying certified Havells HRFR wires, Schneider modular switches, and high-breaking capacity distribution boards directly to site.",
    ctaText: "Explore Electrical",
    ctaAction: "electrical",
    categoryId: "electrical",
    bgImage: "/images/hero/hero-electrical-main.webp",
    mainImage: "/images/hero/hero-electrical-main.webp",
    detailImage: "/images/hero/hero-electrical-detail.webp",
    detailBadge: "1100V Pure Copper Grade",
    sortOrder: 2,
  },
  {
    id: "cement-steel",
    categoryTag: "CEMENT & STEEL",
    headline: "53-Grade Portland Cement & Structural TMT Steel Rebars",
    subtext:
      "Direct depot wholesale pricing and dedicated mini-truck delivery straight to your construction gate in Kathmandu.",
    ctaText: "Request Contractor Bulk Quote",
    ctaAction: "quote",
    categoryId: "construction-materials",
    bgImage: "/images/hero/hero-cement-steel-main.webp",
    mainImage: "/images/hero/hero-cement-steel-main.webp",
    detailImage: "/images/hero/hero-steel-detail.webp",
    detailBadge: "53-Grade & Fe-500D Grade",
    sortOrder: 3,
  },
];

export const categoriesData = [
  {
    id: "power-tools",
    name: "Power Tools",
    slug: "power-tools",
    nameNp: "पावर टूल्स",
    iconKey: "Drill",
    description: "Angle grinders, rotary hammer drills, cordless drivers & circular saws from top brands.",
    productCount: 42,
    imageUrl: "https://images.unsplash.com/photo-1504148455328-c376907d081c?auto=format&fit=crop&fm=webp&w=600&q=80",
    sortOrder: 1,
  },
  {
    id: "hand-tools",
    name: "Hand Tools",
    slug: "hand-tools",
    nameNp: "हातका औजारहरू",
    iconKey: "Hammer",
    description: "Hammers, wrenches, pliers, measuring tapes, and chisels built for endurance.",
    productCount: 68,
    imageUrl: "https://images.unsplash.com/photo-1581783342308-f792dbdd27c5?auto=format&fit=crop&fm=webp&w=600&q=80",
    sortOrder: 2,
  },
  {
    id: "plumbing",
    name: "Plumbing",
    slug: "plumbing",
    nameNp: "प्लम्बिङ सामान",
    iconKey: "Wrench",
    description: "CPVC/PVC pipes, brass ball valves, water pumps, fittings, and leak solutions.",
    productCount: 54,
    imageUrl: "https://images.unsplash.com/photo-1607472586893-edb57bdc0e39?auto=format&fit=crop&fm=webp&w=600&q=80",
    sortOrder: 3,
  },
  {
    id: "electrical",
    name: "Electrical",
    slug: "electrical",
    nameNp: "विद्युतीय सामग्री",
    iconKey: "Zap",
    description: "Copper cables, modular switches, LED battens, MCB distribution boards & conduit pipes.",
    productCount: 75,
    imageUrl: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&fm=webp&w=600&q=80",
    sortOrder: 4,
  },
  {
    id: "fasteners",
    name: "Fasteners & Hardware",
    slug: "fasteners",
    nameNp: "नट-बोल्ट र किल्ला",
    iconKey: "Boxes",
    description: "Expansion anchor bolts, drywall screws, rawl plugs, door hinges and stainless steel nuts.",
    productCount: 90,
    imageUrl: "https://images.unsplash.com/photo-1586864387967-d02ef85d93e8?auto=format&fit=crop&fm=webp&w=600&q=80",
    sortOrder: 5,
  },
  {
    id: "paint-supplies",
    name: "Paint & Supplies",
    slug: "paint-supplies",
    nameNp: "रंग र पेन्ट",
    iconKey: "Paintbrush",
    description: "Weather-resistant exterior paint, interior luxury emulsions, primers, rollers & brushes.",
    productCount: 50,
    imageUrl: "https://images.unsplash.com/photo-1589939705384-5185137a7f0f?auto=format&fit=crop&fm=webp&w=600&q=80",
    sortOrder: 6,
  },
  {
    id: "construction-materials",
    name: "Construction Materials",
    slug: "construction-materials",
    nameNp: "निर्माण सामग्री",
    iconKey: "Building2",
    description: "OPC/PPC Cements, TMT rebars, binding wire, waterproofing chemicals & admixtures.",
    productCount: 36,
    imageUrl: "https://images.unsplash.com/photo-1590069261209-f8e9b8642343?auto=format&fit=crop&fm=webp&w=600&q=80",
    sortOrder: 7,
  },
  {
    id: "safety-equipment",
    name: "Safety Equipment",
    slug: "safety-equipment",
    nameNp: "सुरक्षा उपकरण",
    iconKey: "ShieldCheck",
    description: "Steel-toe boots, industrial helmets, safety harnesses, goggles & respirator masks.",
    productCount: 32,
    imageUrl: "https://images.unsplash.com/photo-1578873375972-005697dca0f3?auto=format&fit=crop&fm=webp&w=600&q=80",
    sortOrder: 8,
  },
  {
    id: "gardening",
    name: "Gardening & Agriculture",
    slug: "gardening",
    nameNp: "बगैंचा र कृषि",
    iconKey: "Trees",
    description: "Braided hose pipes, pruning shears, spray nozzles, shovels & outdoor maintenance tools.",
    productCount: 28,
    imageUrl: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?auto=format&fit=crop&fm=webp&w=600&q=80",
    sortOrder: 9,
  },
  {
    id: "bathroom-sanitary",
    name: "Bathroom & Sanitary",
    slug: "bathroom-sanitary",
    nameNp: "बाथरुम र सेनेटरी",
    iconKey: "Bath",
    description: "Chrome wall mixers, showers, porcelain basins, commodes, stainless sinks & traps.",
    productCount: 45,
    imageUrl: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&fm=webp&w=600&q=80",
    sortOrder: 10,
  },
  {
    id: "adhesives-sealants",
    name: "Adhesives & Sealants",
    slug: "adhesives-sealants",
    nameNp: "गोंद र सिलिकोन",
    iconKey: "FlaskConical",
    description: "Heavy-duty epoxy adhesives, waterproof wood glue, silicone weather sealants & M-Seal.",
    productCount: 26,
    imageUrl: "https://images.unsplash.com/photo-1572981779307-38b8cabb2407?auto=format&fit=crop&fm=webp&w=600&q=80",
    sortOrder: 11,
  },
];

export const brandsData = [
  {
    id: "bosch",
    name: "Bosch",
    slug: "bosch",
    country: "Germany",
    logoUrl: "/images/brands/bosch.webp",
    categoryTags: ["Power Tools", "Measuring Equipment", "Accessories"],
    isAuthorizedPartner: true,
  },
  {
    id: "makita",
    name: "Makita",
    slug: "makita",
    country: "Japan",
    logoUrl: "/images/brands/makita.webp",
    categoryTags: ["Power Tools", "Cordless Systems", "Pneumatics"],
    isAuthorizedPartner: true,
  },
  {
    id: "dewalt",
    name: "DeWalt",
    slug: "dewalt",
    country: "USA",
    logoUrl: "/images/brands/dewalt.webp",
    categoryTags: ["Heavy Duty Tools", "Industrial Drills"],
    isAuthorizedPartner: true,
  },
  {
    id: "asian-paints",
    name: "Asian Paints",
    slug: "asian-paints",
    country: "Nepal / India",
    logoUrl: "/images/brands/asian-paints.webp",
    categoryTags: ["Interior Paint", "Exterior Paint", "Waterproofing"],
    isAuthorizedPartner: true,
  },
  {
    id: "berger",
    name: "Berger Paints",
    slug: "berger",
    country: "India",
    logoUrl: "/images/brands/berger.webp",
    categoryTags: ["Weathercoat", "Primers", "Enamels"],
    isAuthorizedPartner: true,
  },
  {
    id: "astral",
    name: "Astral Pipes",
    slug: "astral",
    country: "India",
    logoUrl: "/images/brands/astral.webp",
    categoryTags: ["CPVC Pipes", "PVC Drainage", "Solvent Cement"],
    isAuthorizedPartner: true,
  },
  {
    id: "havells",
    name: "Havells",
    slug: "havells",
    country: "India",
    logoUrl: "/images/brands/havells.webp",
    categoryTags: ["Copper Cables", "Switches", "Circuit Breakers"],
    isAuthorizedPartner: true,
  },
  {
    id: "schneider",
    name: "Schneider Electric",
    slug: "schneider",
    country: "France",
    logoUrl: "/images/brands/schneider.webp",
    categoryTags: ["Distribution Boards", "MCBs", "Modular Plates"],
    isAuthorizedPartner: true,
  },
  {
    id: "taparia",
    name: "Taparia",
    slug: "taparia",
    country: "India",
    logoUrl: "/images/brands/taparia.webp",
    categoryTags: ["Hand Tools", "Wrench Sets", "Pliers"],
    isAuthorizedPartner: true,
  },
  {
    id: "shivam",
    name: "Shivam Cement",
    slug: "shivam",
    country: "Nepal",
    logoUrl: "/images/brands/shivam.webp",
    categoryTags: ["53 Grade OPC", "PPC Cement"],
    isAuthorizedPartner: true,
  },
  {
    id: "jagdamba",
    name: "Jagdamba Steel",
    slug: "jagdamba",
    country: "Nepal",
    logoUrl: "/images/brands/jagdamba.webp",
    categoryTags: ["Fe-500D TMT Rebars", "Structural Steel"],
    isAuthorizedPartner: true,
  },
  {
    id: "pidilite",
    name: "Pidilite (Fevicol)",
    slug: "pidilite",
    country: "India",
    logoUrl: "/images/brands/pidilite.webp",
    categoryTags: ["Wood Glue", "M-Seal", "Dr. Fixit Waterproofing"],
    isAuthorizedPartner: true,
  },
];

export const testimonialsData = [
  {
    id: "rev-1",
    name: "Er. Rajesh Shrestha",
    role: "Lead Civil Contractor",
    projectTag: "Commercial RCC Construction",
    location: "Sitapaila, Kathmandu",
    photoUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&fm=webp&w=150&q=80",
    rating: 5,
    reviewText:
      "New Adhikari Traders is our go-to partner for all commercial site supplies in Kathmandu. When we poured our 4-storey foundation slab, they delivered 200 sacks of Shivam OPC and TMT steel directly to our Sitapaila site within 4 hours. Transparent pricing and wholesale contractor rates.",
    isVerified: true,
  },
  {
    id: "rev-2",
    name: "Bikash Maharjan",
    role: "Master Plumber & Sanitarian",
    projectTag: "Multi-Unit Apartment Plumbing",
    location: "Mangalbazar, Lalitpur",
    photoUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&fm=webp&w=150&q=80",
    rating: 5,
    reviewText:
      "I have been buying Astral CPVC pipes and Jaquar bath mixers for my clients from New Adhikari Traders for 6 years. Zero fake copies, 100% original fittings. Their staff even helps double check the pipe schedule.",
    isVerified: true,
  },
  {
    id: "rev-3",
    name: "Sunita Tamang",
    role: "Residential Home Builder",
    projectTag: "Two-Story Residence Renovation",
    location: "Budhanilkantha, Kathmandu",
    photoUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&fm=webp&w=150&q=80",
    rating: 5,
    reviewText:
      "Renovating our home was stressful until we found New Adhikari Traders. Bought our Bosch impact drill, Berger Weathercoat paint, and LED lighting package from them. Delivery was quick and packaging was secure.",
    isVerified: true,
  },
  {
    id: "rev-4",
    name: "Prakash Thapa",
    role: "Electrical Contractor & Foreman",
    projectTag: "Factory Wiring & Distribution Boards",
    location: "Balaju Industrial Area, Kathmandu",
    photoUrl: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&fm=webp&w=150&q=80",
    rating: 5,
    reviewText:
      "Finding genuine Havells HRFR pure copper wires in local retail shops is tricky due to duplicates. New Adhikari Traders gives authentic barcode-verified coils with company warranty. Their bulk quote system is very quick.",
    isVerified: true,
  },
];

export const productsData = [
  {
    id: "bosch-gws-600",
    sku: "BOS-GWS-600",
    name: "Bosch GWS 600 Professional Angle Grinder (100mm, 670W)",
    slug: "bosch-gws-600",
    categoryId: "power-tools",
    brandId: "bosch",
    description:
      "Lightweight, compact 670W angle grinder engineered for metal cutting, weld slag removal, and masonry de-burring. Features anti-rotation protective guard and armoured coils that protect motor against sharp grinding dust.",
    technicalSpecs: {
      "Rated Power Input": "670 Watts",
      "No-Load Speed": "11,000 RPM",
      "Disc Diameter": "100 mm (4 inches)",
      "Spindle Thread": "M10",
      Weight: "1.8 kg",
      Voltage: "220V – 240V / 50Hz",
      Warranty: "6 Months Official Nepal Bosch Warranty",
    },
    price: 4850,
    compareAtPrice: 5500,
    stockQuantity: 28,
    unit: "Piece",
    ratingAvg: 4.9,
    ratingCount: 84,
    isBestDeal: true,
    isInStock: true,
    images: [
      "/images/products/bosch-gws-600-1.webp",
      "/images/products/bosch-gws-600-2.webp",
    ],
  },
  {
    id: "makita-df333d-cordless-drill",
    sku: "MAK-DF333D",
    name: "Makita DF333D 12V Max CXT Cordless Driver Drill Kit",
    slug: "makita-df333d-cordless-drill",
    categoryId: "power-tools",
    brandId: "makita",
    description:
      "Compact cordless driver drill with 2-speed mechanical gearing (0-450 & 0-1,700 RPM) and 20 clutch settings. Includes 2x 1.5Ah batteries, fast charger, and heavy-duty blow mold carry case.",
    technicalSpecs: {
      Voltage: "12V Max CXT Lithium-Ion",
      "Max Torque (Hard/Soft)": "30 Nm / 14 Nm",
      "No-Load Speed": "0–450 / 0–1,700 RPM",
      "Chuck Capacity": "0.8 – 10 mm Keyless",
      Weight: "1.1 kg",
      Warranty: "1 Year Official Makita Nepal Warranty",
    },
    price: 11500,
    compareAtPrice: 13200,
    stockQuantity: 14,
    unit: "Kit",
    ratingAvg: 4.8,
    ratingCount: 46,
    isBestDeal: true,
    isInStock: true,
    images: [
      "https://images.unsplash.com/photo-1504148455328-c376907d081c?auto=format&fit=crop&fm=webp&w=700&q=80",
    ],
  },
  {
    id: "dewalt-dwe560-circular-saw",
    sku: "DEW-DWE560",
    name: "DeWalt DWE560 Compact Heavy-Duty Circular Saw (184mm, 1350W)",
    slug: "dewalt-dwe560-circular-saw",
    categoryId: "power-tools",
    brandId: "dewalt",
    description:
      "Compact, lightweight 1350W circular saw delivering 65mm depth of cut. Cutaway inner guard gives improved line of sight to cutting line; dust blower clears dust and debris.",
    technicalSpecs: {
      "Power Input": "1350 Watts",
      "Blade Diameter": "184 mm",
      "Blade Bore": "20 mm",
      "Max Depth of Cut at 90°": "65 mm",
      "No-Load Speed": "5,500 RPM",
      Weight: "3.7 kg",
    },
    price: 13800,
    compareAtPrice: 15500,
    stockQuantity: 9,
    unit: "Piece",
    ratingAvg: 4.9,
    ratingCount: 31,
    isBestDeal: true,
    isInStock: true,
    images: [
      "https://images.unsplash.com/photo-1572981779307-38b8cabb2407?auto=format&fit=crop&fm=webp&w=700&q=80",
    ],
  },
  {
    id: "astral-cpvc-pro-pipe-1inch",
    sku: "AST-CPVC-1IN-3M",
    name: "Astral CPVC PRO SDR 11 Hot & Cold Water Pipe (1 Inch, 3 Meter)",
    slug: "astral-cpvc-pro-pipe-1inch",
    categoryId: "plumbing",
    brandId: "astral",
    description:
      "NSF-certified chlorosulfonated pipe for residential and commercial hot and cold potable water plumbing. Handles temperatures up to 93°C with zero scaling or biological growth.",
    technicalSpecs: {
      Diameter: "1 Inch (25mm Nominal)",
      "Standard Length": "3 Meters (10 Feet)",
      "Pressure Class": "SDR 11 (28 kg/cm² at 23°C)",
      Standards: "IS 15778 / ASTM D2846",
      Jointing: "CPVC Solvent Cement",
    },
    price: 840,
    compareAtPrice: 950,
    stockQuantity: 180,
    unit: "Pipe",
    ratingAvg: 5.0,
    ratingCount: 112,
    isBestDeal: false,
    isInStock: true,
    images: [
      "https://images.unsplash.com/photo-1607472586893-edb57bdc0e39?auto=format&fit=crop&fm=webp&w=700&q=80",
    ],
  },
  {
    id: "havells-lifeline-plus-copper-wire-2-5sqmm",
    sku: "HAV-WIRE-2.5-RED",
    name: "Havells Life Line Plus S3 HRFR Pure Copper Wire 2.5 sq.mm (90m Coil)",
    slug: "havells-lifeline-plus-copper-wire-2-5sqmm",
    categoryId: "electrical",
    brandId: "havells",
    description:
      "Heat resistant, flame retardant pure electrolytic grade copper building wire. 101% conductivity certified with high oxygen and temperature index for fire safety in multi-storey buildings.",
    technicalSpecs: {
      "Conductor Size": "2.5 sq. mm",
      "Coil Length": "90 Meters",
      Insulation: "Dual Layer HRFR PVC (Heat Resistant Flame Retardant)",
      "Voltage Grade": "1100 Volts",
      Color: "Red",
      Certification: "Nepal Bureau of Standards (NS) / ISI",
    },
    price: 5200,
    compareAtPrice: 5800,
    stockQuantity: 45,
    unit: "Coil",
    ratingAvg: 4.9,
    ratingCount: 68,
    isBestDeal: true,
    isInStock: true,
    images: [
      "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&fm=webp&w=700&q=80",
    ],
  },
  {
    id: "berger-weathercoat-anti-dust-20l",
    sku: "BER-WCOAT-20L",
    name: "Berger WeatherCoat Anti-Dust Exterior Luxury Emulsion (20 Liters)",
    slug: "berger-weathercoat-anti-dust-20l",
    categoryId: "paint-supplies",
    brandId: "berger",
    description:
      "Dust-guard technology exterior acrylic emulsion paint designed to protect facades against heavy monsoon rainfall, intense UV rays, and algal growth in Kathmandu Valley.",
    technicalSpecs: {
      Volume: "20 Liters Bucket",
      Finish: "Rich Sheen",
      Coverage: "100–120 sq.ft per liter (2 coats)",
      DryingTime: "Surface Dry: 30 mins; Recoat: 4-6 hours",
      Warranty: "7 Years Performance Warranty",
    },
    price: 14200,
    compareAtPrice: 15800,
    stockQuantity: 18,
    unit: "Bucket",
    ratingAvg: 4.8,
    ratingCount: 39,
    isBestDeal: true,
    isInStock: true,
    images: [
      "https://images.unsplash.com/photo-1589939705384-5185137a7f0f?auto=format&fit=crop&fm=webp&w=700&q=80",
    ],
  },
  {
    id: "shivam-opc-cement-53grade",
    sku: "SHIV-OPC-53",
    name: "Shivam OPC 53-Grade Portland Construction Cement (50kg Bag)",
    slug: "shivam-opc-cement-53grade",
    categoryId: "construction-materials",
    brandId: "shivam",
    description:
      "High-early strength 53 grade Ordinary Portland Cement for structural pillars, foundation slabs, beams, and high-load civil infrastructure across Kathmandu.",
    technicalSpecs: {
      Weight: "50 kg Paper Sacks",
      Grade: "53 Grade OPC",
      Standard: "NS-49 / IS 12269",
      CompressiveStrength: "53+ MPa at 28 days",
      Application: "Columns, Beams, Retaining Walls, RCC Slabs",
    },
    price: 780,
    compareAtPrice: 850,
    stockQuantity: 450,
    unit: "Bag",
    ratingAvg: 5.0,
    ratingCount: 195,
    isBestDeal: false,
    isInStock: true,
    images: [
      "https://images.unsplash.com/photo-1590069261209-f8e9b8642343?auto=format&fit=crop&fm=webp&w=700&q=80",
    ],
  },
  {
    id: "taparia-spanner-set-12pcs",
    sku: "TAP-SPAN-12",
    name: "Taparia Double Ended Open Jaw Spanner Set (12 Pieces 6mm-32mm)",
    slug: "taparia-spanner-set-12pcs",
    categoryId: "hand-tools",
    brandId: "taparia",
    description:
      "Drop forged from high-grade carbon steel with chrome plating for rust protection. Accurately broached jaws provide secure fastener grip without rounding bolt edges.",
    technicalSpecs: {
      Pieces: "12 Pieces (6x7, 8x9, 10x11, 12x13, 14x15, 16x17, 18x19, 20x22, 21x23, 24x27, 25x28, 30x32 mm)",
      Material: "Drop Forged Chrome Vanadium Alloy",
      Finish: "Nickel Chrome Plated",
      Standards: "IS 2028-1998",
    },
    price: 1950,
    compareAtPrice: 2300,
    stockQuantity: 36,
    unit: "Set",
    ratingAvg: 4.9,
    ratingCount: 77,
    isBestDeal: true,
    isInStock: true,
    images: [
      "https://images.unsplash.com/photo-1581783342308-f792dbdd27c5?auto=format&fit=crop&fm=webp&w=700&q=80",
    ],
  },
];
